version: '3.7'

services:
    latex:
        # build: .
        image: sumeshi/md2latex:latest
        volumes:
            - '.:/opt'
        working_dir: /opt
        command: bash -c "npm install && npm run start"
        